[workspace]
members = [
    "app",
    "schema-manager",
    "database",
    "api",
    "entities",
    "fields", "json-cache",
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
