[package]
name = "authz"
version = "0.1.0"
edition = "2021"

[dependencies]
cedar-policy = "3.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
thiserror = "1.0"