# System Configuration for Development Environment
id: system
name: System Configuration
description: Core system configuration for Marain CMS
provider: core
version: 1.0.0
values:
  # Application settings
  app:
    name: "MarainCMS"
    environment: "dev"
    debug: true
    
  # Logging configuration
  logging:
    level: "info"
    format: "json"
    file: "./data/logs/marain_cms.log"
    
  # Database configuration
  database:
    default: "sqlite"
    connections:
      sqlite:
        driver: "sqlite3"
        file: "content/marain.db"  # Relative to DATA_PATH
        timeout: 5000
        pragmas:
          foreign_keys: true
          journal_mode: "wal"
  
  # JSON Cache configuration (ReDB)
  json_cache:
    enabled: true
    file: "json-cache/marain_json_cache.db"  # Relative to DATA_PATH
    default_ttl: 86400  # 24 hours in seconds
    max_size_mb: 100  # Maximum cache size in MB
    eviction_policy: "lru"  # Least Recently Used
    auto_evict_expired: true  # Automatically remove expired entries
    eviction_interval: 3600  # Check for expired entries every hour (seconds)
  
  # User Database configuration
  user_database:
    enabled: true
    file: "user-backend/marain_user.db"  # Relative to DATA_PATH
    max_connections: 5
    connection_timeout: 30  # seconds
    
  # Secure Log configuration
  secure_log:
    enabled: true
    file: "user-backend/secure.log"  # Relative to DATA_PATH
    max_size_mb: 100  # Maximum log file size before rotation
    max_rotations: 10  # Number of rotated log files to keep
    enable_verification: true  # Enable cryptographic hash verification
    rotation_check_interval: 300  # Check for rotation every 5 minutes (seconds)
  
  # WebAuthn configuration for PassKey authentication
  webauthn:
    rp_id: "localhost"
    rp_name: "Marain CMS"
    rp_origin: "http://localhost:3043"
    timeout_ms: 60000
    attestation: "none"  # none, indirect, or direct
    user_verification: "preferred"  # required, preferred, or discouraged
    
  # Session configuration
  session:
    cookie_name: "marain_session"
    timeout_seconds: 86400  # 24 hours
    secure: false  # Set to true in production with HTTPS
    same_site: "lax"  # strict, lax, or none
    http_only: true
    
  # Magic link email configuration
  magic_link:
    smtp_host: "smtp.gmail.com"
    smtp_port: 587
    smtp_username: ""  # Set via environment variable SMTP_USERNAME
    smtp_password: ""  # Set via environment variable SMTP_PASSWORD
    from_email: "noreply@marain.local"
    from_name: "Marain CMS"
    token_expiry_minutes: 15
    email_template: |
      <h2>Your Magic Link</h2>
      <p>Click the link below to sign in to Marain CMS:</p>
      <p><a href="{link}">{link}</a></p>
      <p>This link will expire in 15 minutes.</p>