# System Configuration for Development Environment
id: system
name: System Configuration
description: Core system configuration for Marain CMS
provider: core
version: 1.0.0
values:
  # Application settings
  app:
    name: "MarainCMS"
    environment: "dev"
    debug: true
    
  # Logging configuration
  logging:
    level: "info"
    format: "json"
    file: "./data/logs/marain_cms.log"
    
  # Database configuration
  database:
    default: "sqlite"
    connections:
      sqlite:
        driver: "sqlite3"
        file: "content/marain.db"  # Relative to DATA_PATH
        timeout: 5000
        pragmas:
          foreign_keys: true
          journal_mode: "wal"
  
  # JSON Cache configuration (ReDB)
  json_cache:
    enabled: true
    file: "json-cache/marain_json_cache.db"  # Relative to DATA_PATH
    default_ttl: 86400  # 24 hours in seconds
    max_size_mb: 100  # Maximum cache size in MB
    eviction_policy: "lru"  # Least Recently Used
    auto_evict_expired: true  # Automatically remove expired entries
    eviction_interval: 3600  # Check for expired entries every hour (seconds)
  
  # User Database configuration
  user_database:
    enabled: true
    file: "user-backend/marain_user.db"  # Relative to DATA_PATH
    max_connections: 5
    connection_timeout: 30  # seconds
    
  # Secure Log configuration
  secure_log:
    enabled: true
    file: "user-backend/secure.log"  # Relative to DATA_PATH
    max_size_mb: 100  # Maximum log file size before rotation
    max_rotations: 10  # Number of rotated log files to keep
    enable_verification: true  # Enable cryptographic hash verification
    rotation_check_interval: 300  # Check for rotation every 5 minutes (seconds)